services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-crud:latest
    container_name: user-crud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
