apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud
  labels:
    app: user-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-crud
  template:
    metadata:
      labels:
        app: user-crud
    spec:
      containers:
        - name: user-crud
          image: user-crud:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
