apiVersion: v1
kind: Service
metadata:
  name: user-crud
  labels:
    app: user-crud
spec:
  type: NodePort
  selector:
    app: user-crud
  ports:
    - name: http
      port: 80
      targetPort: 8081
